export const contactFaqs = [
  {
    question: "How fast can you deliver a quote?",
    answer:
      "We aim to share quotes within 4 to 8 business hours for standard jobs. Send your DXF, DWG, STEP, IGES, or PDF drawings with material details for the fastest response.",
  },
  {
    question: "What file formats do you accept?",
    answer:
      "We accept DXF, DWG, STEP, IGES, PDF drawings, and hand-marked sketches. Our team reviews every submission for manufacturability before production.",
  },
  {
    question: "What is your minimum order quantity?",
    answer:
      "We support everything from one-off prototypes to repeat production batches, depending on the process, material, and delivery schedule.",
  },
  {
    question: "Do you offer on-site pickup?",
    answer:
      "Yes. You can arrange pickup from our Kamrej, Surat, Gujarat facility, and we can also coordinate dispatch across India.",
  },
] as const;

export const siteConfig = {
  name: "Balaji Engineering Works",
  legalName: "Balaji Engineering Works",
  shortName: "Balaji Engineering",
  alternateName: "Sheet Metal Bending Works",
  url:
    process.env.NEXT_PUBLIC_SITE_URL || "https://www.metalsheetbending.com",
  ogImage: "/opengraph.jpg",
  description:
    "Balaji Engineering Works is a Surat-based manufacturer and service provider for CNC laser cutting services in Surat, CNC plasma cutting services in Surat, CNC plate bending service in Surat, sheet metal fabrication, and industrial products including base plates, foundation bolts, purlins, perforated sheets, and heavy fabrication.",
  phone: "+919978753398",
  phoneDisplay: "+91 84888 01197",
  email: "mayankpokiya3@gmail.com",
  foundingDate: "2001",
  priceRange: "$$",
  gstNumber: "24BCUPS8314Q1ZK",
  businessType: "Manufacturer and Service Provider",
  locale: "en_IN",
  language: "en-IN",
  indiaMartProfile: "https://www.balajiengineeringworks.in/",
  serviceAreas: [
    "Surat",
    "Kamrej",
    "Bharuch",
    "Ankleshwar",
    "Vapi",
    "Vadodara",
    "Ahmedabad",
    "Gujarat",
    "Maharashtra",
    "Mumbai",
    "Rajasthan",
    "Madhya Pradesh",
    "India",
  ],
  industries: [
    "Sheet Metal Fabrication",
    "Sheet Metal Forming",
    "Sheet Metal Forming Industries Surat",
    "Structural Steel Fabrication",
    "CNC Laser Cutting",
    "CNC Plasma Cutting",
    "Steel Shearing",
    "Steel Plate Bending",
    "Press Brake Bending",
    "Plate Rolling",
    "Profile Cutting",
    "Steel Punching",
    "Heavy Fabrication",
    "Industrial Manufacturing",
    "Industrial Product Manufacturing",
    "Structural Steel Components",
  ],
  keywords: [
    // === BRAND ===
    "Balaji Engineering Works",
    "Balaji Engineering Works Surat",
    "balaji engineering surat",
    "balaji engineering gujarat",
    "balaji sheet metal works",
    // === SHEET METAL BENDING — PRIMARY FOCUS ===
    "sheet metal bending",
    "sheet metal bending works",
    "sheet metal bending service",
    "sheet metal bending surat",
    "sheet metal bending gujarat",
    "sheet metal bending india",
    "sheet metal bending near me",
    "sheet metal bending company",
    "sheet metal bending manufacturer",
    "sheet metal bending supplier",
    "sheet metal bending contractor",
    "sheet metal bending shop",
    "sheet metal bending workshop",
    "sheet metal bending factory",
    "sheet metal bending job work",
    "sheet metal bending price",
    "sheet metal bending cost",
    "sheet metal bending rate",
    "sheet metal bending quote",
    "custom sheet metal bending",
    "precision sheet metal bending",
    "quality sheet metal bending",
    "metal sheet bending",
    "metal sheet bending surat",
    "sheet bending service",
    "sheet bending service surat",
    "sheet bending works",
    "sheet bending company",
    "metal bending service",
    "metal bending works",
    "steel sheet bending",
    "steel bending service",
    "industrial sheet bending",
    // === CNC BENDING & PRESS BRAKE ===
    "CNC bending service",
    "CNC bending surat",
    "CNC bending gujarat",
    "CNC bending india",
    "CNC bending near me",
    "CNC bending company",
    "CNC bending price",
    "CNC bending rate",
    "CNC bending job work",
    "CNC press brake bending",
    "CNC press brake surat",
    "CNC press brake service",
    "press brake bending",
    "press brake bending service",
    "press brake bending surat",
    "press brake bending gujarat",
    "press brake bending india",
    "press brake bending near me",
    "press brake bending company",
    "press brake service",
    "press brake job work",
    "press brake bending price",
    "press brake bending rate",
    "press brake bending quote",
    "hydraulic press brake service",
    "heavy duty press brake bending",
    "V bending service",
    "U bending service",
    "Z bending service",
    "box bending service",
    "complex shape bending",
    "multi-bend fabrication",
    // === PLATE BENDING ===
    "plate bending service",
    "plate bending works",
    "plate bending surat",
    "plate bending gujarat",
    "plate bending india",
    "plate bending near me",
    "plate bending company",
    "plate bending manufacturer",
    "plate bending supplier",
    "plate bending job work",
    "plate bending price",
    "plate bending rate",
    "plate bending quote",
    "cnc plate bending",
    "cnc plate bending service",
    "cnc plate bending surat",
    "cnc plate bending gujarat",
    "heavy plate bending",
    "thick plate bending",
    "thin sheet bending",
    "channel bending service",
    "angle bending service",
    "flat bar bending",
    // === CNC LASER CUTTING ===
    "CNC laser cutting",
    "CNC laser cutting service",
    "CNC laser cutting surat",
    "CNC laser cutting gujarat",
    "CNC laser cutting india",
    "CNC laser cutting near me",
    "CNC laser cutting company",
    "CNC laser cutting manufacturer",
    "CNC laser cutting supplier",
    "CNC laser cutting price",
    "CNC laser cutting cost",
    "CNC laser cutting rate",
    "CNC laser cutting rate per kg",
    "CNC laser cutting quote",
    "CNC laser cutting job work",
    "laser cutting service",
    "laser cutting works",
    "laser cutting surat",
    "laser cutting gujarat",
    "laser cutting india",
    "laser cutting near me",
    "laser cutting company",
    "laser cutting manufacturer",
    "laser cutting supplier",
    "laser cutting price",
    "laser cutting price per kg",
    "laser cutting price per meter",
    "laser cutting cost",
    "laser cutting rate",
    "laser cutting quote",
    "laser cutting job work",
    "fiber laser cutting",
    "fiber laser cutting service",
    "fiber laser cutting surat",
    "fiber laser cutting india",
    "2D laser cutting",
    "laser sheet cutting",
    "laser plate cutting",
    "laser profile cutting",
    "DXF laser cutting",
    "DXF file laser cutting service",
    "custom laser cutting",
    "precision laser cutting",
    "sheet metal laser cutting",
    "MS laser cutting",
    "SS laser cutting",
    "aluminum laser cutting",
    // === CNC PLASMA CUTTING ===
    "CNC plasma cutting",
    "CNC plasma cutting service",
    "CNC plasma cutting surat",
    "CNC plasma cutting gujarat",
    "CNC plasma cutting india",
    "CNC plasma cutting near me",
    "CNC plasma cutting company",
    "CNC plasma cutting price",
    "CNC plasma cutting rate",
    "CNC plasma cutting job work",
    "plasma cutting service",
    "plasma cutting works",
    "plasma cutting surat",
    "plasma cutting india",
    "plasma cutting near me",
    "plasma cutting company",
    "plasma cutting price",
    "plasma cutting rate",
    "plasma cutting job work",
    "heavy plate plasma cutting",
    "thick plate plasma cutting",
    "MS plasma cutting",
    "steel plasma cutting",
    // === PLATE ROLLING ===
    "plate rolling service",
    "plate rolling surat",
    "plate rolling gujarat",
    "plate rolling india",
    "plate rolling company",
    "plate rolling price",
    "plate rolling job work",
    "cylinder rolling service",
    "cone rolling service",
    "pipe rolling service",
    "pipe rolling surat",
    "shell rolling service",
    "drum rolling service",
    "tank shell rolling",
    "pressure vessel rolling",
    "plate rolling and bending",
    // === PROFILE CUTTING ===
    "profile cutting service",
    "profile cutting surat",
    "CNC profile cutting",
    "steel profile cutting",
    "MS profile cutting",
    "plasma profile cutting",
    "laser profile cutting",
    "flat bar cutting service",
    "angle cutting service",
    "channel cutting service",
    "beam cutting service",
    // === SHEET METAL FABRICATION ===
    "sheet metal fabrication",
    "sheet metal fabrication service",
    "sheet metal fabrication surat",
    "sheet metal fabrication gujarat",
    "sheet metal fabrication india",
    "sheet metal fabrication near me",
    "sheet metal fabrication company",
    "sheet metal fabrication manufacturer",
    "sheet metal fabrication supplier",
    "sheet metal fabrication workshop",
    "sheet metal fabrication price",
    "sheet metal fabrication cost",
    "sheet metal fabrication quote",
    "sheet metal fabrication job work",
    "custom sheet metal fabrication",
    "precision sheet metal fabrication",
    "heavy sheet metal fabrication",
    "heavy fabrication surat",
    "heavy fabrication india",
    "heavy fabrication company",
    "industrial sheet metal fabrication",
    "structural sheet metal fabrication",
    "sheet metal parts manufacturer",
    "sheet metal components manufacturer",
    "sheet metal products manufacturer",
    "sheet metal parts supplier",
    "sheet metal component supplier",
    "sheet metal forming service",
    "sheet metal shearing",
    "sheet metal punching",
    "sheet metal cutting",
    "contract sheet metal fabrication",
    "outsource sheet metal fabrication",
    "B2B sheet metal fabrication",
    "bulk sheet metal fabrication",
    "prototype sheet metal fabrication",
    "STEP file fabrication",
    "DWG file metal fabrication",
    // === MATERIALS ===
    "mild steel fabrication",
    "MS sheet metal fabrication",
    "MS sheet cutting",
    "MS plate cutting",
    "MS plate bending",
    "MS fabrication surat",
    "mild steel plate bending service",
    "mild steel laser cutting",
    "stainless steel fabrication",
    "stainless steel sheet cutting",
    "stainless steel laser cutting",
    "stainless steel bending",
    "SS 304 fabrication",
    "SS 316 fabrication",
    "SS 202 fabrication",
    "SS sheet cutting surat",
    "CRCA sheet bending",
    "CRCA sheet cutting",
    "CRCA sheet fabrication",
    "HR sheet fabrication",
    "HR plate fabrication",
    "hot rolled steel fabrication",
    "cold rolled steel fabrication",
    "galvanized sheet fabrication",
    "galvanized iron sheet cutting",
    "GI sheet fabrication",
    "GI sheet cutting",
    "GI sheet bending",
    "galvanized sheet bending surat",
    "aluminum sheet fabrication",
    "aluminum bending service",
    "aluminum sheet cutting",
    "aluminium fabrication surat",
    "carbon steel fabrication",
    "structural steel fabrication",
    "high tensile steel fabrication",
    "boiler quality steel cutting",
    "pressure vessel steel fabrication",
    // === PRODUCTS — BASE PLATES ===
    "base plate manufacturer",
    "MS base plate manufacturer",
    "base plate manufacturer surat",
    "base plate manufacturer gujarat",
    "base plate manufacturer india",
    "MS base plate supplier",
    "base plate supplier surat",
    "custom base plate fabrication",
    "column base plate manufacturer",
    "steel base plate manufacturer",
    "anchor base plate manufacturer",
    "structural base plate manufacturer",
    "base plates for steel structures",
    "base plates for buildings",
    "base plate wholesale surat",
    "base plate bulk order india",
    // === PRODUCTS — FOUNDATION BOLTS ===
    "foundation bolt manufacturer",
    "foundation bolt manufacturer surat",
    "foundation bolt manufacturer gujarat",
    "foundation bolt manufacturer india",
    "foundation bolt supplier surat",
    "foundation bolts wholesale",
    "MS foundation bolt manufacturer",
    "anchor bolt manufacturer",
    "anchor bolt manufacturer surat",
    "anchor bolt supplier",
    "J type foundation bolt",
    "L type foundation bolt",
    "U type foundation bolt",
    "bent anchor bolt manufacturer",
    "custom foundation bolt",
    "forged foundation bolt",
    "foundation bolt price surat",
    "foundation bolt bulk order",
    "heavy duty anchor bolt",
    "M16 foundation bolt",
    "M20 foundation bolt",
    "M24 foundation bolt",
    "M30 foundation bolt",
    "M36 foundation bolt",
    // === PRODUCTS — PURLINS ===
    "purlin manufacturer",
    "purlin manufacturer surat",
    "purlin manufacturer gujarat",
    "purlin manufacturer india",
    "purlin supplier surat",
    "c purlin manufacturer",
    "c purlin manufacturer surat",
    "z purlin manufacturer",
    "z purlin manufacturer surat",
    "c and z purlin manufacturer surat",
    "steel purlin manufacturer",
    "MS purlin manufacturer",
    "roofing purlin manufacturer",
    "structural purlin manufacturer",
    "purlin for shed",
    "purlin for warehouse",
    "purlin for factory",
    "purlin for industrial building",
    "purlin price surat",
    "purlin wholesale india",
    "cold formed purlin",
    "light gauge steel purlin",
    // === PRODUCTS — PERFORATED SHEETS ===
    "perforated sheet manufacturer",
    "perforated sheet manufacturer surat",
    "perforated sheet manufacturer gujarat",
    "perforated sheet manufacturer india",
    "perforated sheet supplier surat",
    "MS perforated sheet manufacturer",
    "SS perforated sheet manufacturer",
    "GI perforated sheet manufacturer",
    "aluminum perforated sheet",
    "round hole perforated sheet",
    "square hole perforated sheet",
    "custom perforated sheet",
    "perforated sheet price surat",
    "perforated sheet wholesale",
    "acoustic perforated sheet",
    "ventilation perforated sheet",
    // === PRODUCTS — DECKING & ROOFING ===
    "decking sheet supplier surat",
    "decking sheet manufacturer surat",
    "floor decking sheet",
    "roof decking sheet",
    "metal decking supplier",
    "steel decking supplier",
    "decking sheet price surat",
    "corrugated sheet manufacturer surat",
    "corrugated roofing sheet surat",
    "corrugated metal sheet supplier",
    "GI corrugated sheet",
    "roofing sheet supplier surat",
    "roofing sheet manufacturer surat",
    "metal roofing supplier",
    "industrial roofing sheet surat",
    // === PRODUCTS — STEEL PALLETS ===
    "steel pallet manufacturer",
    "steel pallet manufacturer surat",
    "steel pallet manufacturer gujarat",
    "MS pallet manufacturer surat",
    "metal pallet manufacturer",
    "industrial pallet manufacturer",
    "heavy duty steel pallet",
    "custom steel pallet",
    "warehouse pallet manufacturer",
    "steel pallet wholesale",
    "steel pallet bulk order",
    // === PRODUCTS — WALKWAY & STRUCTURAL ===
    "walkway plank manufacturer surat",
    "roof walkway plank",
    "industrial walkway plank",
    "steel walkway plank",
    "catwalk plank manufacturer",
    "anti-slip walkway plank",
    "chequered plate supplier surat",
    "chequered plate cutting surat",
    "MS angle manufacturer surat",
    "MS channel manufacturer surat",
    "structural steel components surat",
    "steel structure fabrication surat",
    "MS flat bar manufacturer surat",
    "conveyor stringer fabrication",
    "conveyor component fabrication",
    "conveyor frame fabrication",
    "material handling fabrication",
    "industrial conveyor parts",
    // === INDUSTRIES SERVED ===
    "sheet metal for chemical industry",
    "sheet metal for petrochemical",
    "sheet metal for oil and gas",
    "sheet metal for pharma industry",
    "sheet metal for pharmaceutical plant",
    "sheet metal for food processing",
    "sheet metal for food industry",
    "automotive sheet metal fabrication",
    "sheet metal for automobile",
    "sheet metal for construction",
    "construction steel fabrication",
    "sheet metal for real estate",
    "sheet metal for building construction",
    "sheet metal for infrastructure",
    "sheet metal for power plant",
    "sheet metal for solar energy",
    "solar mounting frame fabrication",
    "sheet metal for sugar industry",
    "sheet metal for textile industry",
    "sheet metal for cement industry",
    "sheet metal for mining",
    "sheet metal for warehouse",
    "sheet metal for industrial shed",
    "sheet metal for cold storage",
    "sheet metal for water treatment",
    "sheet metal for HVAC",
    "ductwork fabrication",
    // === WELDING SERVICES ===
    "MIG welding fabrication",
    "MIG welding surat",
    "TIG welding fabrication",
    "TIG welding surat",
    "arc welding fabrication",
    "welding fabrication surat",
    "structural welding surat",
    "heavy welding fabrication",
    "steel welding fabrication",
    "custom welding fabrication",
    // === BUYER INTENT — PRICE & QUOTE ===
    "sheet metal fabrication price india",
    "laser cutting price india",
    "plasma cutting price india",
    "plate bending price india",
    "sheet metal fabrication cost india",
    "get a quote sheet metal",
    "free quote sheet metal fabrication",
    "sheet metal fabrication estimate",
    "sheet metal bending rate per kg",
    "laser cutting rate per kg",
    "laser cutting rate per meter",
    "plasma cutting rate per kg",
    "plate bending rate per kg",
    "sheet metal job work rate",
    "bulk fabrication price",
    "contract fabrication price",
    "sheet metal bending price surat",
    "laser cutting price surat",
    "plasma cutting price surat",
    // === BUYER INTENT — SUPPLIER / MANUFACTURER ===
    "sheet metal fabrication manufacturer india",
    "sheet metal supplier india",
    "steel fabricator india",
    "sheet metal company india",
    "best sheet metal fabricator india",
    "top sheet metal fabricator surat",
    "reliable sheet metal supplier india",
    "trusted steel fabricator india",
    "sheet metal fabrication export",
    "export sheet metal fabricated parts",
    "steel fabricated components export india",
    "sheet metal supplier surat",
    "steel fabricator surat",
    // === BUYER INTENT — JOB WORK & B2B ===
    "sheet metal job work",
    "sheet metal job work surat",
    "sheet metal job work india",
    "laser cutting job work surat",
    "laser cutting job work india",
    "plasma cutting job work surat",
    "plasma cutting job work india",
    "plate bending job work surat",
    "sheet metal job work contractor",
    "CNC job work surat",
    "CNC job work gujarat",
    "job work fabrication india",
    "job work steel fabrication",
    "contract manufacturing sheet metal",
    "contract fabrication steel india",
    "outsource sheet metal fabrication india",
    "outsource laser cutting india",
    "B2B sheet metal india",
    "B2B steel fabrication india",
    "B2B laser cutting india",
    "bulk order sheet metal",
    "bulk order laser cutting",
    "bulk order plate bending",
    "wholesale sheet metal fabrication",
    "prototype sheet metal india",
    "small batch sheet metal fabrication",
    "large batch sheet metal fabrication",
    "repeat order sheet metal",
    "DXF file fabrication",
    "DWG file fabrication",
    "STEP file fabrication",
    "IGES file fabrication",
    "CAD drawing fabrication",
    // === LOCATION — SURAT ===
    "sheet metal fabrication surat",
    "steel fabrication surat",
    "laser cutting surat",
    "plasma cutting surat",
    "plate bending surat",
    "press brake surat",
    "sheet metal works surat",
    "fabrication company surat",
    "metal works surat",
    "sheet metal near me surat",
    "sheet metal fabrication kamrej",
    "steel fabrication kamrej",
    // === LOCATION — GUJARAT ===
    "sheet metal fabrication gujarat",
    "steel fabrication gujarat",
    "laser cutting gujarat",
    "plasma cutting gujarat",
    "plate bending gujarat",
    "sheet metal supplier gujarat",
    "sheet metal manufacturer gujarat",
    "steel fabricator gujarat",
    "CNC laser cutting gujarat",
    "CNC bending gujarat",
    "sheet metal fabrication bharuch",
    "laser cutting bharuch",
    "steel fabrication bharuch",
    "sheet metal bending bharuch",
    "sheet metal fabrication ankleshwar",
    "laser cutting ankleshwar",
    "steel fabrication ankleshwar",
    "sheet metal fabrication vapi",
    "laser cutting vapi",
    "sheet metal fabrication vadodara",
    "laser cutting vadodara",
    "steel fabrication vadodara",
    "sheet metal fabrication rajkot",
    "laser cutting rajkot",
    "sheet metal fabrication ahmedabad",
    "laser cutting ahmedabad",
    "steel fabrication ahmedabad",
    "sheet metal fabrication gandhinagar",
    // === LOCATION — MAHARASHTRA ===
    "sheet metal fabrication maharashtra",
    "sheet metal fabrication mumbai",
    "laser cutting mumbai",
    "steel fabrication mumbai",
    "sheet metal supplier mumbai",
    "sheet metal fabrication pune",
    "laser cutting pune",
    "sheet metal fabrication nashik",
    "sheet metal fabrication thane",
    "sheet metal fabrication navi mumbai",
    // === LOCATION — INDIA ===
    "sheet metal fabrication india",
    "steel fabrication india",
    "laser cutting india",
    "plasma cutting india",
    "plate bending india",
    "sheet metal supplier india",
    "sheet metal manufacturer india",
    "pan india steel fabrication",
    "nationwide sheet metal supplier",
    "all india sheet metal supplier",
    "all india delivery fabrication",
    "sheet metal fabrication rajasthan",
    "sheet metal fabrication madhya pradesh",
    "heavy fabrication company india",
    // === WORLDWIDE / EXPORT ===
    "sheet metal fabrication export india",
    "steel fabricated parts export",
    "laser cut parts export india",
    "custom fabrication export",
    "B2B sheet metal worldwide",
    "sheet metal parts supplier worldwide",
    "steel fabrication for export",
    "industrial fabrication export india",
    "precision laser cut parts worldwide",
    "custom sheet metal parts global",
    "steel component manufacturer india export",
    "sheet metal export from india",
    // === LONG-TAIL SEARCH PHRASES ===
    "sheet metal bending works near me",
    "CNC laser cutting service near me",
    "CNC plasma cutting service near me",
    "press brake bending near me",
    "best CNC laser cutting company surat",
    "CNC plate bending company in gujarat",
    "industrial fabrication company surat gujarat india",
    "MS base plate manufacturer in surat gujarat",
    "foundation bolt manufacturer in surat india",
    "c purlin z purlin manufacturer surat",
    "perforated sheet manufacturer in surat gujarat",
    "steel pallet manufacturer in surat gujarat",
    "custom steel fabrication company india",
    "B2B sheet metal parts supplier india",
    "laser cut sheet metal parts india",
    "sheet metal job work company surat",
    "CNC bending and cutting service surat",
    "plate rolling and bending service surat",
    "structural steel fabrication company surat",
    "heavy fabrication company surat gujarat",
    "industrial sheet metal manufacturer surat",
    "steel components manufacturer surat gujarat",
    "quick turnaround sheet metal fabrication",
    "urgent laser cutting job work surat",
    "sheet metal parts for construction india",
    "steel base plates for towers",
    "anchor bolts for buildings india",
    "foundation bolts for industrial plants",
    "purlins for warehouse roofing india",
    "perforated sheets for filtration",
    "steel pallets for warehouse storage",
    "industrial steel components manufacturer india",
    "custom metal parts fabrication india",
    "sheet metal bending and laser cutting surat",
    "CNC fabrication company surat gujarat",
    "sheet metal works company near me",
    "get quote sheet metal fabrication india",
    "sheet metal bending rate list surat",
    "laser cutting service for industrial use",
    "press brake bending for construction",
    "plate bending for pressure vessels",
    "sheet metal fabrication for pharma plants",
    "metal fabrication for chemical tanks",
    "bulk sheet metal order india",
    "sheet metal contract manufacturing india",
    "outsource sheet metal bending india",
    "laser cutting for OEM manufacturers india",
    "sheet metal components for OEM",
    "precision CNC fabrication surat india",
  ],
  address: {
    streetAddress:
      "Kamrej, Surat, Gujarat",
    locality: "Surat",
    region: "Gujarat",
    postalCode: "394185",
    country: "IN",
  },
  mapUrl:
    "https://maps.google.com/?q=Balaji+Engineering+Works+Plot+No.+11+12+Soham+Industrial+Estate+NH+8+Kamrej+Surat+Gujarat+394185",
} as const;
